/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Administrador;

import static Administrador.Principal.Escritorio;
import javax.swing.JOptionPane;

/**
 *
 * @author edin1
 */
public class VistaAdmin extends javax.swing.JInternalFrame {

    /**
     * Creates new form Vista
     */
    public VistaAdmin() {
        initComponents();
        actualizarTabla();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jpanelSucuarsal = new javax.swing.JPanel();
        jpanelProducto = new javax.swing.JPanel();
        jpanelCliente = new javax.swing.JPanel();
        jpanelVendedor = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        btnCrear = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        scrollPane1 = new java.awt.ScrollPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        Tabla = new javax.swing.JTable();
        jButton2 = new javax.swing.JButton();

        jpanelSucuarsal.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jpanelSucuarsalLayout = new javax.swing.GroupLayout(jpanelSucuarsal);
        jpanelSucuarsal.setLayout(jpanelSucuarsalLayout);
        jpanelSucuarsalLayout.setHorizontalGroup(
            jpanelSucuarsalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );
        jpanelSucuarsalLayout.setVerticalGroup(
            jpanelSucuarsalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Sucursales", jpanelSucuarsal);

        jpanelProducto.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jpanelProductoLayout = new javax.swing.GroupLayout(jpanelProducto);
        jpanelProducto.setLayout(jpanelProductoLayout);
        jpanelProductoLayout.setHorizontalGroup(
            jpanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );
        jpanelProductoLayout.setVerticalGroup(
            jpanelProductoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Productos", jpanelProducto);

        jpanelCliente.setBackground(new java.awt.Color(153, 204, 255));

        javax.swing.GroupLayout jpanelClienteLayout = new javax.swing.GroupLayout(jpanelCliente);
        jpanelCliente.setLayout(jpanelClienteLayout);
        jpanelClienteLayout.setHorizontalGroup(
            jpanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 746, Short.MAX_VALUE)
        );
        jpanelClienteLayout.setVerticalGroup(
            jpanelClienteLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 449, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Clientes", jpanelCliente);

        jpanelVendedor.setBackground(new java.awt.Color(153, 204, 255));

        jButton1.setText("Carga Maxima");

        btnCrear.setText("Crear");
        btnCrear.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                btnCrearMouseEntered(evt);
            }
        });
        btnCrear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearActionPerformed(evt);
            }
        });

        jButton3.setText("Actualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Exportar Listado a PDF");

        Tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(Tabla);

        scrollPane1.add(jScrollPane1);

        jButton2.setText("Salir");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jpanelVendedorLayout = new javax.swing.GroupLayout(jpanelVendedor);
        jpanelVendedor.setLayout(jpanelVendedorLayout);
        jpanelVendedorLayout.setHorizontalGroup(
            jpanelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jpanelVendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(scrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 424, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jpanelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelVendedorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jpanelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(jpanelVendedorLayout.createSequentialGroup()
                                    .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jpanelVendedorLayout.createSequentialGroup()
                                    .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        jpanelVendedorLayout.setVerticalGroup(
            jpanelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jpanelVendedorLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jpanelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jpanelVendedorLayout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addGroup(jpanelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(btnCrear, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jpanelVendedorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(212, 212, 212)
                        .addComponent(jButton2))
                    .addComponent(scrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Vendedores", jpanelVendedor);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 751, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 477, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
public static boolean banderaboton = true;
    public static boolean banderaGuardarActualizar = true;
    public static int nu;
    Controlador controlador = new Controlador();

    private void btnCrearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearActionPerformed

        if (banderaboton) {
            Escritorio.add(vendedorCrear);
            vendedorCrear.show();
            banderaboton = false;
            vendedorCrear.lblTitulo.setText("Nuevo Vendedor");
            vendedorCrear.jbtnGuardar_Actualizar.setText("Guardar");
        }

    }//GEN-LAST:event_btnCrearActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (Tabla.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, " debemos sleccionar una fila");
        } else {
            if (banderaboton) {
                Escritorio.add(vendedorCrear);
                vendedorCrear.show();
                actualizar(Tabla.getSelectedRow());
                banderaboton = false;
                banderaGuardarActualizar = false;
                vendedorCrear.lblTitulo.setText("Actualizar Vendedor");
                vendedorCrear.jbtnGuardar_Actualizar.setText("Actualizar");
                nu = Tabla.getSelectedRow();
            }

        }
// TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btnCrearMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnCrearMouseEntered
        actualizarTabla();            // TODO add your handling code here:
    }//GEN-LAST:event_btnCrearMouseEntered

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (Tabla.getSelectedRow() < 0) {
            JOptionPane.showMessageDialog(null, " debemos sleccionar una fila");
        } else {
            Modelo.datos.remove(Tabla.getSelectedRow());
            actualizarTabla();
        }  // TODO add your handling code here:
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
Escritorio.remove(this);
Principal.Bandera=true;
    }//GEN-LAST:event_jButton2ActionPerformed
    Modificar_GuardarVentas vendedorCrear = new Modificar_GuardarVentas();

    void actualizarTabla() {
        Tabla.setModel(controlador.TablaVentas());
    }

    public void actualizar(int id) {
        vendedorCrear.jtflCaja.setText(Modelo.datos.get(id).getCaja() + "");
        vendedorCrear.jtflGenero.setText(Modelo.datos.get(id).getGenero() + "");
        vendedorCrear.jtflNombre.setText(Modelo.datos.get(id).getNombre() + "");
        vendedorCrear.jtflVentas.setText(Modelo.datos.get(id).getVentas() + "");
        vendedorCrear.jtflcodigo.setText(Modelo.datos.get(id).getCodigo() + "");
        vendedorCrear.jPassword.setText(Modelo.datos.get(id).getPassword() + "");
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable Tabla;
    private javax.swing.JButton btnCrear;
    public static javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    public static javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    public static javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JPanel jpanelCliente;
    private javax.swing.JPanel jpanelProducto;
    private javax.swing.JPanel jpanelSucuarsal;
    private javax.swing.JPanel jpanelVendedor;
    private java.awt.ScrollPane scrollPane1;
    // End of variables declaration//GEN-END:variables
}
